name: Build Windows Server 2019

on:  
  push:
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-2019

    steps:
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Checkout
        uses: actions/checkout@v2
       
      - name: CMake Build
        run: |
          mkdir "${{ runner.workspace }}\_build"
          cd "${{ runner.workspace }}\_build"
          
          cmake %GITHUB_WORKSPACE% -DCMAKE_INSTALL_PREFIX=_install
          cmake --build .
          cmake --build . --target install
        shell: cmd
        
      - name: Upload Windows setup
        uses: actions/upload-artifact@v2
        with:
          name: windows-setup
          path: ${{ runner.workspace }}/_build/_install/*       